<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.z6ii.BG' shared service.

return $this->privates['.service_locator.z6ii.BG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'unitRepository' => ['privates', 'App\\Repository\\UnitRepository', 'getUnitRepositoryService.php', true],
], [
    'unitRepository' => 'App\\Repository\\UnitRepository',
]);
