<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.oSVaTF.' shared service.

return $this->privates['.service_locator.oSVaTF.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'usrRepository' => ['privates', 'App\\Repository\\UsrRepository', 'getUsrRepositoryService.php', true],
], [
    'usrRepository' => 'App\\Repository\\UsrRepository',
]);
