<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.8G4X907' shared service.

return $this->privates['.service_locator.8G4X907'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'unit' => ['privates', '.errored..service_locator.8G4X907.App\\Entity\\Unit', NULL, 'Cannot autowire service ".service_locator.8G4X907": it references class "App\\Entity\\Unit" but no such service exists.'],
], [
    'unit' => 'App\\Entity\\Unit',
]);
