<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.o13nwiM' shared service.

return $this->privates['.service_locator.o13nwiM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'country' => ['privates', '.errored..service_locator.o13nwiM.App\\Entity\\Country', NULL, 'Cannot autowire service ".service_locator.o13nwiM": it references class "App\\Entity\\Country" but no such service exists.'],
], [
    'country' => 'App\\Entity\\Country',
]);
