<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.Qk86g1f' shared service.

return $this->privates['.service_locator.Qk86g1f'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'city' => ['privates', '.errored..service_locator.Qk86g1f.App\\Entity\\City', NULL, 'Cannot autowire service ".service_locator.Qk86g1f": it references class "App\\Entity\\City" but no such service exists.'],
], [
    'city' => 'App\\Entity\\City',
]);
