<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.9eJVjQZ' shared service.

return $this->privates['.service_locator.9eJVjQZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'stationRepository' => ['privates', 'App\\Repository\\StationRepository', 'getStationRepositoryService.php', true],
], [
    'stationRepository' => 'App\\Repository\\StationRepository',
]);
