<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator...Emfax' shared service.

return $this->privates['.service_locator...Emfax'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'cityRepository' => ['privates', 'App\\Repository\\CityRepository', 'getCityRepositoryService.php', true],
], [
    'cityRepository' => 'App\\Repository\\CityRepository',
]);
