<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWZ1XtP7\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWZ1XtP7/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWZ1XtP7.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWZ1XtP7\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerWZ1XtP7\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'WZ1XtP7',
    'container.build_id' => '9551a983',
    'container.build_time' => 1563318468,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWZ1XtP7');
